### ISSUE TITLE
should `--verbose` be default?

### ISSUE THREAD

**Issue by tkossak** [cs01/pipx#34]
I think `--verbose` should be the default option. When you execute for example `pipx install borgbackup` (or whatever that takes a bit longer) and you wait a while for anything to happen, you start wondering if pipx froze. Some feedback that something IS happening (and what) would be nice, before somebody tries to kill the process.

pipx 0.0.0.13

**Comment by cs01** [comment]
I agree that it would be nice to have some feedback that it's still working during long operations. I think the way to go here is some kind of animation in the terminal in non-verbose mode rather than adding verbose text. With the `--verbose` flag, no animation will be needed. I'll try to add something.

**Comment by tkossak** [comment]
If not whole `--verbose` output, then It would be nice to know at least what dependencies are being installed.

**Comment by cs01** [comment]
I am going to keep the output minimal by default because I think in the wide majority of cases users don't care which dependencies are being installed by pip -- they are just using pipx to install the binaries. I added text in v0.0.0.14 that lets the user know pipx is working if it starts taking too long. 

If the user really wants to know what dependencies are being installed, the verbose option is always there. And really pipx does not add much output of its own, so verbose is basically like a pip install.
